services:
  vember-os:
    build: .
    container_name: vember_hub
    stdin_open: true 
    tty: true
    # Use host mode to bypass the virtual bridge entirely
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    environment:
      - TERM=xterm-256color
      - COLORTERM=truecolor
    volumes:
      - .:/app 
      - /app/.venv
      - ./nodes:/app/nodes
      - ./data:/app/data
      - /sys:/sys:ro
