services:
  vember-os: # <--- Line 3: Ensure 2 spaces here
    build: . # <--- Line 4: Ensure 4 spaces here
    container_name: vember_hub
    stdin_open: true 
    tty: true
    network_mode: "host"
    environment:
      - TERM=xterm-256color
      - COLORTERM=truecolor
    volumes:
      - .:/app 
      - /app/.venv
      - ./ops:/app/ops
      - ./data:/app/data
      - /sys:/sys:ro
      - /sys/class/thermal:/sys/class/thermal:ro
      - /sys/class/hwmon:/sys/class/hwmon:ro