"""
================================================================================
🔱 VEMBER-OS: VANGUARD CONTRACT PASSPORT
================================================================================
Family Stack:  DEVELOPER_CORE
Node Identity: VANGUARD_SHIELD_NODE
Context Path:  /dev/vanguard.py

Environmental Integrity, Dependency Mapping & Logic Validation.
Authorized and signed under Vember OS decentralized system specifications.

Context Actions:
[V]     TRIGGER_INTEGRITY_SCAN
[L]     LOCK_DEPENDENCY_HASHES
[BKSP]  RETURN_TO_ROOT_CLI
================================================================================
"""

import json, subprocess
from pathlib import Path

from rich.panel import Panel
from rich.table import Table
from rich.columns import Columns
from rich.align import Align
from assets.branding import VemberAssets

Theme = VemberAssets.THEME


class Vanguard:
	"""Protects the environment via uv dependency audits and logic validation."""

	def __init__(self):
		self.selection = 0
		self.active_node = "Environmental HUD"
		self.node_output = "[dim]Awaiting integrity scan...[/]"
		self.is_processing = False

		self.test_results = {"passed": 0, "failed": 0, "total": 0}

		self.test_failures = []
		self.menu_items = [
			{"label": "Audit Packages", "desc": "Map uv managed dependencies"},
			{"label": "Validate Logic", "desc": "Engage pytest suite"},
		]

	def render(self):
		"""Returns the UI component for the VemberCLI host controller."""

		# Menu Panel
		menu_table = Table(box=None, padding=(0, 1), show_header=False)
		for i, item in enumerate(self.menu_items):
			# Using 'primary' for ACCENT
			style = f"bold {Theme.primary}" if i == self.selection else "dim"
			prefix = f"[{Theme.primary}]▶[/]" if i == self.selection else "  "
			menu_table.add_row(prefix, f"[{style}]{item['label']}[/]")

		left_panel = Panel(
			menu_table,
			title=f"[{Theme.primary}]VANGUARD ACTIONS[/]",
			border_style=Theme.primary, # Changed from ACCENT
			width=30,
			padding=(1, 2),
		)

		# Integrity HUD Panel
		right_stack = Table.grid(padding=1)
		right_stack.add_row(
			Panel(
				self.node_output,
				title=f"[{Theme.primary}]INTEGRITY HUD[/]",
				border_style=Theme.primary if self.is_processing else Theme.secondary,
				width=46,
				padding=(1, 2),
			)
		)

		connector = Table.grid()
		connector.add_row(f" [{Theme.primary}]══▶[/] ")

		return Align.center(
			Columns([left_panel, Align.center(connector), right_stack], align="center")
		)
	
	def load_test_results(self):
		"""Reads the json report generated by the TestReporter."""
		report_path = Path("exports/test_results.json")
		if report_path.exists():
			with open(report_path, "r") as f:
				data = json.load(f)
				# Parse summary from pytest-json-report format
				summary = data.get("summary", {})
				self.test_results["passed"] = summary.get("passed", 0)
				self.test_results["failed"] = summary.get("failed", 0)
				self.node_output = (
					f"Tests: [green]{self.test_results['passed']} Passed[/] | "
					f"[red]{self.test_results['failed']} Failed[/]"
				)
		else:
			self.node_output = "[dim]No report found. Run 'Validate Logic' to generate.[/]"

	def run_integrity_scan(self):
		"""Engages pytest and pipes the report to the exports district."""
		self.is_processing = True
		self.node_output = "[yellow]Scanning district...[/]"
		
		try:
			# Engage the integrity scan
			result = subprocess.run(
				["uv", "run", "pytest", "--json-report", "--json-report-file=exports/test_results.json", "tests/"],
				capture_output=True,
				text=True
			)
			self.load_test_results()
		except Exception as e:
			self.node_output = f"[bold red]SCAN FAILED:[/] {str(e)}"
		finally:
			self.is_processing = False
